import jsPDF from 'jspdf';
import { Career } from '@/data/types';

export function generateCareerPDF(career: Career, matchPercentage: number, userName?: string) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(22, 130, 112); // primary color
  doc.rect(0, 0, w, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('CareerCompass', 14, 18);
  doc.setFontSize(12);
  doc.text('Your Personalized Career Plan', 14, 28);
  doc.setFontSize(10);
  doc.text(`Match: ${matchPercentage}%`, w - 14, 18, { align: 'right' });
  if (userName) {
    doc.text(`Prepared for: ${userName}`, w - 14, 28, { align: 'right' });
  }

  y = 50;
  doc.setTextColor(30, 30, 30);

  // Career title
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(career.name, 14, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const descLines = doc.splitTextToSize(career.description, w - 28);
  doc.text(descLines, 14, y);
  y += descLines.length * 5 + 8;

  // Quick Facts
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Quick Facts', 14, y);
  y += 7;

  const facts = [
    ['Group Required', career.group],
    ['Duration', career.duration],
    ['Salary Range', career.salaryRange],
    ['Difficulty', career.difficulty],
    ['Growth Rate', career.growthRate],
  ];
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  facts.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}: `, 14, y);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 14 + doc.getTextWidth(`${label}: `), y);
    y += 6;
  });
  y += 4;

  // Skills
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Skills to Develop', 14, y);
  y += 7;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  career.skills.forEach(skill => {
    doc.text(`• ${skill}`, 18, y);
    y += 5;
  });
  y += 4;

  // Roadmap
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Career Roadmap', 14, y);
  y += 7;
  doc.setFontSize(10);
  career.roadmap.forEach((step, i) => {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.text(`${i + 1}. ${step.title} (${step.duration})`, 18, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    const stepLines = doc.splitTextToSize(step.description, w - 40);
    doc.text(stepLines, 22, y);
    y += stepLines.length * 5 + 3;
  });
  y += 4;

  // Certifications
  if (y > 250) { doc.addPage(); y = 20; }
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Recommended Certifications', 14, y);
  y += 7;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  career.certifications.forEach(cert => {
    doc.text(`• ${cert}`, 18, y);
    y += 5;
  });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by CareerCompass | careercompass.app', 14, doc.internal.pageSize.getHeight() - 10);
    doc.text(`Page ${i} of ${pageCount}`, w - 14, doc.internal.pageSize.getHeight() - 10, { align: 'right' });
  }

  doc.save(`CareerPlan-${career.name.replace(/\s+/g, '-')}.pdf`);
}
